services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    healthcheck:
      test: ["CMD", "sh", "-c", "wget -q --spider http://127.0.0.1:11434/api/tags || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 20s

  
  api:
    image: python:3.11-slim
    container_name: health-rag-api
    command: >
      bash -c "pip install -r requirements.txt &&
               uvicorn app.api:app --host 0.0.0.0 --port 8000 --log-level info"
    env_file:
      - .env
    volumes:
      - ./:/workspace
    working_dir: /workspace
    ports:
      - "8000:8000"
    depends_on:
      - ollama

  ui:
    image: python:3.11-slim
    container_name: health-rag-ui
    command: >
      bash -c "pip install -r requirements.txt &&
               streamlit run app/streamlit_app.py --server.port 8501 --browser.gatherUsageStats false"
    env_file:
      - .env
    volumes:
      - ./:/workspace
    working_dir: /workspace
    ports:
      - "8501:8501"
    depends_on:
      api:
        condition: service_started

volumes:
  ollama:
